project:
  type: website
  output-dir: rendered

website:
  title: "Melandri Lab @ the University of Arizona"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



